# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mobile_no', models.IntegerField(max_length=10)),
                ('company', models.CharField(max_length=200)),
                ('visiting', models.CharField(max_length=100)),
            ],
        ),
    ]
